# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-02 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='descrtptioon',
            new_name='description',
        ),
    ]
